repos:
  - repo: git@github.com:psf/black.git
    rev: 24.4.2
    hooks:
      - id: black
        language_version: "3.11"

  - repo: git@github.com:pre-commit/mirrors-mypy.git
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies: ["types-PyYAML"]

  - repo: git@github.com:PyCQA/isort.git
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
