version: "3.8"
services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-05-28T17-19-04Z.fips
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    volumes:
      - ${MINIO_VOLUME_MOUNTPOINT}:/data:Z
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}

volumes:
  minio_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MINIO_VOLUME_MOUNTPOINT}